name: Generate Sitemap

on:
  push:
    branches:
      - main
  workflow_dispatch:



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate Sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          path-to-root: .
          sitemap-format: xml

      - name: Commit and push sitemap
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add sitemap.xml
          git commit -m 'Generate sitemap' || echo "No changes to commit"
          git push
